#[client]
#showSidebarNavigation = false
#[theme]
#base = "dark"
#textColor = "#FFC0CB"

[client]
showSidebarNavigation = false
[theme]
primaryColor = "#74fffc"
textColor = "c5aaff"
backgroundColor = "white"